modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs_create&mc=2001&loader=forge"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_create"
version = "${version}"
displayName = "KubeJS Create"
authors = "LatvianModder"
description = '''
KubeJS Create integration
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_create]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4-build.95,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_create]]
modId = "create"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"