modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs_create&mc=2101&loader=neoforge"
license = "MIT"

[[mods]]
modId = "kubejs_create"
version = "${version}"
displayName = "KubeJS Create"
authors = "latvian.dev"
description = '''
KubeJS Create integration
'''
logoFile = "kubejs_create_logo.png"
modUrl = "https://kubejs.com"
displayURL = "https://kubejs.com"

[[dependencies.kubejs_create]]
modId = "kubejs"
mandatory = true
versionRange = "[${kubejs_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_create]]
modId = "create"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "kubejs_create.mixins.json"